package exporter

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/baditaflorin/civitas/internal/evidence"
)

func Markdown(item evidence.Case, docs []evidence.Document, appVersion, commit, format string) string {
	orderedDocs := append([]evidence.Document(nil), docs...)
	sort.SliceStable(orderedDocs, func(i, j int) bool {
		return orderedDocs[i].ID < orderedDocs[j].ID
	})

	var builder strings.Builder
	builder.WriteString("# " + item.Title + "\n\n")
	builder.WriteString("Generated by Civitas safe publishing export.\n\n")
	builder.WriteString("## Export metadata\n\n")
	builder.WriteString("- schema_version: phase2.export.v1\n")
	builder.WriteString("- app_version: " + appVersion + "\n")
	builder.WriteString("- commit: " + commit + "\n")
	builder.WriteString("- format: " + format + "\n")
	builder.WriteString("- parameters: deterministic-order, redacted-contact-details, confidence-visible\n")
	builder.WriteString("- document_count: " + fmt.Sprint(len(orderedDocs)) + "\n\n")
	for _, doc := range orderedDocs {
		builder.WriteString("## " + doc.Filename + "\n\n")
		builder.WriteString("- source_id: " + doc.ID + "\n")
		builder.WriteString("- source_sha256: " + doc.SHA256 + "\n")
		builder.WriteString("- shape: " + doc.Shape + "\n")
		builder.WriteString("- state: " + doc.State + "\n")
		fmt.Fprintf(&builder, "- confidence: %.2f\n", doc.Confidence)
		builder.WriteString("- schema_version: " + doc.Provenance.SchemaVersion + "\n")
		builder.WriteString("- source_app_version: " + doc.Provenance.AppVersion + "\n")
		builder.WriteString("- processor_parameters: " + strings.Join(doc.Provenance.Parameters, ", ") + "\n\n")
		builder.WriteString(Redact(doc.Summary) + "\n\n")
		if len(doc.Fields) > 0 {
			builder.WriteString("Inferred fields:\n\n")
			for _, field := range doc.Fields {
				fmt.Fprintf(&builder, "- %s (%s, %.2f): %s\n", field.Name, field.Type, field.Confidence, Redact(field.Value))
			}
			builder.WriteString("\n")
		}
		if len(doc.Anomalies) > 0 {
			builder.WriteString("Warnings and next steps:\n\n")
			for _, anomaly := range doc.Anomalies {
				fmt.Fprintf(&builder, "- %s: %s Next: %s\n", anomaly.Code, anomaly.Message, anomaly.NextStep)
			}
			builder.WriteString("\n")
		}
		if len(doc.Entities) > 0 {
			builder.WriteString("Entities retained as categories, with direct contact details redacted.\n\n")
			for _, entity := range doc.Entities {
				fmt.Fprintf(&builder, "- %s: %s\n", entity.Type, Redact(entity.Value))
			}
			builder.WriteString("\n")
		}
	}
	return builder.String()
}

func StableExportID(caseID, format, body string) string {
	sum := sha256.Sum256([]byte(caseID + "\x00" + format + "\x00" + body))
	return "export_" + hex.EncodeToString(sum[:])[:16]
}

func Redact(value string) string {
	email := regexp.MustCompile(`(?i)\b[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}\b`)
	phone := regexp.MustCompile(`\b(?:\+?\d[\d .()\-]{7,}\d)\b`)
	value = email.ReplaceAllString(value, "[redacted-email]")
	return phone.ReplaceAllString(value, "[redacted-phone]")
}
